kind: pipeline
name: stage-0

steps:
- name: show-files
  image: alpine
  commands:
    - /bin/sh -ex | ls -R

---
kind: pipeline
name: stage-1

step:
- name: pdfid
  #image: cincan/pdfid
  image: alpine
  commands:
    - echo "test"
    - docker pull cincan/pdfid
    - docker run -v "${PWD}:/pdf-source" -e SSH_PRIV_KEY="${SSH_PRIV_KEY}" -e GITLAB_USER_EMAIL="${DRONE_COMMIT_AUTHOR_EMAIL}" -e GITLAB_USER_ID="${DRONE_COMMIT_AUTHOR_NAME}" --entrypoint "/bin/sh" cincan/pdfid /pdf-source/pdfid.sh

- name: peepdf
  #image: cincan/peepdf
  environment:
    SSH_PRIV_KEY:
      from_secret: SSH_PRIV_KEY
  commands:
    - echo "test"
    - docker pull cincan/peepdf
    - docker run -v "${PWD}:/pdf-source" -e SSH_PRIV_KEY="${SSH_PRIV_KEY}" -e GITLAB_USER_EMAIL="${DRONE_COMMIT_AUTHOR_EMAIL}" -e GITLAB_USER_ID="${DRONE_COMMIT_AUTHOR_NAME}" --entrypoint "/bin/bash" cincan/peepdf /pdf-source/peepdf-vt.sh

depends_on:
  - stage-0

---
kind: pipeline
name: stage-2

step:
- name: jsunpackn
  #image: cincan/jsunpack-n
  commands:
    - /bin/bash/ results/jsunpackn.sh

depends_on:
  - stage-1

---
kind: pipeline
name: stage-3

step:
- name: sctest
  #image: cincan/peepdf
  commands:
    - /bin/bash/ results/sctest.sh

depends_on:
  - stage-2
