image: docker:git

before_script:
  - apk add --update openssh-client bash git
  #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIV_KEY" | ssh-add -
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name  "$GITLAB_USER_ID"
  - git remote set-url --push origin git@gitlab.com:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
  - echo "ending before script..."

services:
  - docker:dind

stages:
  - stage-0-list-files
  - stage-1-scan
  - stage-2-scan
  - stage-3-scan

show-files:
  stage: stage-0-list-files
  script:
    - /bin/sh -ex | ls -R
  artifacts:
    name: pdf-files
  only:
    - pdf-source

pdfid:
  stage: stage-1-scan
  #image: 
  #  name: cincan/pdfid
  #  entrypoint: ["/usr/bin/python","pdfid/pdfid.py"]
  script:
    - docker pull cincan/pdfid
    - /bin/bash pdfid.sh
  only:
    - pdf-source
  artifacts:
    name: output-files

peepdf-virustotal-check:
  stage: stage-1-scan
  #image: 
  #  name: cincan/peepdf
  #  entrypoint: ["/usr/bin/python","/peepdf/peepdf.py"]
  script:
    - docker pull cincan/peepdf
    - /bin/bash peepdf-vt.sh
  artifacts:
    name: output-files
  only:
    - pdf-source

jsunpackn:
  stage: stage-2-scan
  dependencies: [pdfid]
  #image: 
  #  name: cincan/jsunpack-n
  #  entrypoint: ["/usr/bin/python","/jsunpack-n/jsunpackn.py"]
  script:
    - apk add --no-cache python3
    #- apt-get install python3
    - docker pull cincan/jsunpack-n
    - /bin/bash jsunpackn.sh
  artifacts:
    name: output-files
  only:
    - pdf-source

job-sctest:
  stage: stage-3-scan
  dependencies: [jsunpackn]
  #image: 
  #  name: cincan/peepdf
  #  entrypoint: ["/usr/bin/python","/peepdf/peepdf.py"]
  script:
    - docker pull cincan/peepdf
    - /bin/bash sctest.sh
    - git push origin HEAD:master
  artifacts:
    name: output-files
  only:
    - pdf-source
